#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f top2.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace top2.sv mux.sv delay.sv lfsr.sv top1.sv f1fsm.sv clktick.sv --exe top2_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop2.mk Vtop2


obj_dir/Vtop2
